### ISSUE TITLE
don't read data from github but rather the local server

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-benchmark#12]
Currently, the data is read from github when displaying graphs, this has the problem that this project can only ever be used for exactly one repository without forking and changing the code. Instead, the server should provide the data to render.

**Comment by humancalico** [comment]
Earlier the server did provide the data along with it. This was changed so that it would be easier to change and upload your own data files (possibly with an upload button in the future)
The downside of this is that the startup time for the website is now a lot slower than it was before. We should probably add a Loading component to the charts as well for this.

**Comment by Licenser** [comment]
The idea was around but it was to have an option to load data with the goal to let people visualize their own data. And in the end discarded. The state right now is the opposite, it lets no one other than the repository owner visualize their data, loading it from the server would allow people to read using their own data.

The JSON isn't a long-term sustainable solution anyway, it will need to end up in some kind of manageable database so loading from the server is the sensible way to go.

letting people visualize their own data is a nice to have gimmick but it is getting in the way of the service being usable for a feature that no one is and very likely will ever use.
